
script:
  - cd cgi-bin && perl -c -MO=Lint ./page.fcgi '' && perl -c -Mwarnings::unused ./page.fcgi ''
  - rootdir=$(pwd)/.. perl page.fcgi page=albums

language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  # - "5.30-extras"
  - "5.28-extras"
  - "5.26-extras"
  - "5.24-extras"
  - "5.22-extras"
  # - "5.20-extras"
  # - "5.18-extras"

sudo: false

before_install:
  # Needed for Locale::Object
  - cpanm --installdeps --quiet --notest DBD::SQLite
  - cpanm --notest --quiet DBD::SQLite Locale::Object::Country Gzip::Faster
  # - sudo apt-get update -q
  # - sudo apt-get install -y libdb-dev libyaml-syck-perl libchi-perl libconfig-auto-perl libnet-oauth-perl

install:
  # - sudo apt-get install -y liblog-log4perl-perl libtemplate-perl liburi-perl libio-aio-perl
  - cpanm --skip-satisfied -q -n autodie warnings::unused FCGI Log::Log4perl CGI::Carp CGI::Info CGI::Lingua FCGI::Buffer File::HomeDir Log::WarnDie Template::Plugin::EnvHash HTML::SocialMedia File::pfopen Log::Any::Adapter::Log4perl Text::CSV::Slurp B::Lint Error Config::Auto CHI Log::Dispatch::File YAML::Any Mo DBD::CSV Text::xSV::Slurp YAML::XS CGI::ACL IPC::System::Simple

script:
  - cd cgi-bin && perl -c -MO=Lint ./page.fcgi '' && perl -c -Mwarnings::unused ./page.fcgi ''
  - rootdir=$(pwd)/../.. perl page.fcgi page=albums
  - rootdir=$(pwd)/../.. perl page.fcgi page=sections section='Stock%20or%20(1,2\)=(select*from(select%20name_const(CHAR(111,108,111,108,111,115,104,101,114\),1\),name_const(CHAR( <-- HERE 111,108,111,108,111,115,104,101,114\),1\)\)a\)%20--%20and%201%3D1'
